### ISSUE TITLE
Save images using Sketch

### ISSUE THREAD

**Issue by snk4tr** [daihase/Sketch#16]
Hey there! Thanks for you awesome job!

I try to build an image editing app using your library. Got a question there: how can I save the image to the gallery after I loaded and edited it in the app?

I tried to somehow get  a `UIImage` object from the SketchView and then save it in a traditional way to the gallery using `UIImageWriteToSavedPhotosAlbum`, but did not succeed. I don't see any method in SketchView AP for image saving either. 

Thank you!

**Comment by snk4tr** [comment]
@daihase thank you for your suggestion but I don't really understand how to use provided API for image saving. Initially I expected `SketchView ` to have such method since it has one for image loading. 

I've also tried the following ways to save image:
* Save using standard IOS API for that:
```python
@IBAction func save(_ sender: AnyObject) {
        guard let selectedImage = sketchView.image else {
            print("Image not found!")
            return
        }
        UIImageWriteToSavedPhotosAlbum(selectedImage, self, #selector(image(_:didFinishSavingWithError:contextInfo:)), nil)
    }
```
It appeared that `sketchView.image ` is private for some reason so it's not accessible from the outer scope.

* Save using context as a source of the image. The code is similar to the previous one:
```python
@IBAction func save(_ sender: AnyObject) {
        selectedImage = UIGraphicsGetImageFromCurrentImageContext()
        UIImageWriteToSavedPhotosAlbum(selectedImage, self, #selector(image(_:didFinishSavingWithError:contextInfo:)), nil)
    }
```

Neither of methods worked, but I still wanna use your library. Please provide a code snippet if possible which shows how to save edited image to gallery. Thanks.

**Comment by daihase** [comment]
@snk4tr 
I see.
Actually Sketch has a function to read images as you say, but there is no function to save.

So I made a [sample](https://github.com/daihase/iOS_Sample/tree/master/Sketch_saveAlbum) to save the canvas image by Sketch in the gallery. (Please decide the name of the album by yourself. For now it's name is "Sample_App")

Please refer to this sample.

![01](https://user-images.githubusercontent.com/19318060/49684208-f8af7980-fb13-11e8-8a3b-790d3188fe6f.png)
![02](https://user-images.githubusercontent.com/19318060/49684209-f8af7980-fb13-11e8-8900-27371ee1dcb6.png)
![03](https://user-images.githubusercontent.com/19318060/49684211-f8af7980-fb13-11e8-9360-2253c533c607.png)
![04](https://user-images.githubusercontent.com/19318060/49684212-f9481000-fb13-11e8-9ace-d6126697278b.png)

**Comment by snk4tr** [comment]
@daihase that's exactly what I want and it works perfectly! Thanks a lot for your help!
