### ISSUE TITLE
How can I resize stamp when adding

### ISSUE THREAD

**Issue by longnh2604** [daihase/Sketch#2]
Could you give option or suggest some way to scale/resize stamp when adding to the drawing screen.
Thanks so much.

**Comment by daihase** [comment]
Sorry for the late reply.
By executing the following code, Sketch reads the image in Assets.xcassets and displays it on the screen.

`
 sketchView.stampImage = UIImage(named: "stampName")
`

If you want to resize the image before it is displayed on the screen, you can define a resize function before it and set the resized UIImage to sketchView.stampImage as it is, you can display dynamically resized image on the screen.

**Comment by longnh2604** [comment]
Sorry to open this again, I'm trying to add stamp into drawing vc but I still can not get it work. Could you please give me some advice ?
I need to resize the stamp on the screen so I have add gestures(pinch,pan) and a button to confirm when it completed to remove the gestures and get the location of its.
@objc func onAddStampConfirm(sender: UIButton!) {

        //remove gesture
        for subview in sketchView.subviews {
            for recognizer in subview.gestureRecognizers ?? [] {
                subview.removeGestureRecognizer(recognizer)
            }
        }
        
        sketchView.drawTool = .stamp
        self.sketchView.stampImage = imvStamp.image
        let cgPoint = CGPoint.init(x: imvStamp.frame.origin.x, y: imvStamp.frame.origin.y)
        self.sketchView.addStampComplete(position: cgPoint)
    }

And in sketchView class, I've added this to regconize when add stamp complete
public func addStampComplete(position:CGPoint) {
        currentTool = toolWithCurrentSettings()
        guard let stampTool = currentTool as? StampTool else { return }
        pathArray.add(stampTool)
        stampTool.setStampImage(image: stampImage)
        stampTool.setInitialPoint(position)
        finishDrawing()
    }

in touchbegan (case is StampTool) I let it blank.
Thanks
