### ISSUE TITLE
For android

### ISSUE THREAD

**Issue by edbrix-school** [daihase/Sketch#36]
Is you have your library support for android or do you have any other library like this for android?

**Comment by daihase** [comment]
I don't know if there are any other library for Android. 
But, I think it is not hard to draw on Canvas. Please refer to the link below.

ref: [How to Create a Paint Application in Android?](https://www.geeksforgeeks.org/how-to-create-a-paint-application-in-android/)

I hope it will be helpful to you.

**Comment by edbrix-school** [comment]
> I don't know if there are any other library for Android.
> But, I think it is not hard to draw on Canvas. Please refer to the link below.
> 
> ref: [How to Create a Paint Application in Android?](https://www.geeksforgeeks.org/how-to-create-a-paint-application-in-android/)
> 
> I hope it will be helpful to you.

Ok,Thank you.
