### ISSUE TITLE
Support Privacy Manifests?

### ISSUE THREAD

**Issue by mrs1669** [daihase/Sketch#43]
Does Sketch SDK support Privacy Manifest?

Quoted [Apple official website](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests)
> Important
Third-party SDKs need to provide their own privacy manifest files that record the types of data they collect. Your app’s privacy manifest file doesn’t need to cover data collected by third-party SDKs that your app links to.

Sketch SDK is not included in the SDKs that are subject to the privacy manifest and signature requirement, but if you are not using the required reason API, we would like to know if you have any plans to address this issue by stating that you are not using the required reason API (i.e., not including anything in the required reason API).

---

Sketch SDK は Privacy Manifestご対応される予定はありますでしょうか？
Apple公式(日本語): https://developer.apple.com/jp/support/third-party-SDK-requirements/ 

Sketch SDKはプライバシーマニフェストと署名必須の対象となるSDK には含まれておりませんが、required reason API 等を利用していないようであれば、利用してないことを記載 (何もrequired reason APIに含めない) していただく等の対応のご予定があるかお伺いしたく存じます。

**Comment by daihase** [comment]
@mrs1669 
I apologize for the delayed response.

As you mentioned, our library does not use any specific API, and I believe it's necessary to make modifications to indicate that.

I will address this within this month.
Thank you for alerting me at an early stage.

---
早い段階でアラートを投げてくださっていたのに、返答が遅れて申し訳ありません！
こちらおっしゃる通り利用してない旨を示す改修は必要と考えております。
今月中に対応致しますでお待ちいただけますでしょうか。
よろしくお願いします。
